apiVersion: testapp.github.com/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: webserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: webserver-operator
  name: redis-sample
spec:
  # TODO(user): Add fields here
